server:
  address: "0.0.0.0"
  port: 8080
  read_timeout: 10s
  write_timeout: 10s
  idle_timeout: 120s
  shutdown_timeout: 30s

upstream:
  url: "http://localhost:9000"
  timeout: 30s
  max_idle_conns: 100
  max_conns_per_host: 100
  idle_conn_timeout: 90s
  tls_handshake_timeout: 10s
  forbidden_headers:
    - "Authorization"
    - "Cookie"
    - "Set-Cookie"

cache:
  enabled: true
  max_size: 104857600  # 100 MB
  default_ttl: 5m
  respect_cache_control: true
  type: "memory"  # "memory" or "redis"
  redis:
    address: "localhost:6379"
    password: ""
    db: 0

ratelimit:
  enabled: true
  requests_per_second: 100
  burst: 200
  by_ip: true
  by_api_key: false
  api_key_header: "X-API-Key"

logging:
  level: "info"  # debug, info, warn, error
  format: "json"  # json or console
  output_path: "stdout"

metrics:
  enabled: true
  path: "/metrics"
  port: 9090

